### PR TITLE
Implement ability to add dates to a road trip

### PR DESCRIPTION
**Pull request by Jennak21**
The organiser is now able to add dates to their road trip using airbnb's react-date-range component

image

Changes:

- Wrapper component displaying spinner is shown while itinerary data is being fetched
- A calendar modal to select dates using AirBnB's react-date-range component 
- Data structure of itinerary has been changed. It now has an array of days - a day has a date and an array of itinerary items.

Note to reviewers:
- Please test that the button and calendar modal shows only if you are the organiser and if there is no existing itinerary
- I am unsure about the file structure of the Itinerary folder in components

Closes #47

### CODE REVIEW

**Review by Denijar — CHANGES_REQUESTED** [review]
image
I got this error when I ran `npm start` for the frontend. I think the `itinerary` folder in `components` needs to have a capital I.

**Comment by Denijar** [comment]
hmm I am wondering about the text contrast. So before I have "clicked" on the end date the text is black and I think it would be more readable if it was white.
image

Then when I click maybe it would be more readable if the light pink was slightlyy darker. I think having white text is nice but maybe the contrast could be stronger? Maybe Flynn has thoughts about this too haha

image

**Comment by Jennak21** [comment]
> hmm I am wondering about the text contrast. So before I have "clicked" on the end date the text is black and I think it would be nice if it was white.
> image
> 
> Then when I click maybe it would be more readable if the light pink was slightlyy darker. I think having white text is nice but maybe the contrast could be stronger? Maybe Flynn has thoughts about this too haha
> 
> image

Good point! I definitely like the white text. Maybe this is something that can be discussed later and changed later.

**Comment by Jennak21** [comment]
> image
> I got this error when I ran `npm start` for the frontend. I think the `itinerary` folder in `components` needs to have a capital I.

Ah right, forgot Git has trouble picking up on the capitalization of a directory. Will get that fixed :) Thanks!

**Comment by Jennak21** [comment]
> > hmm I am wondering about the text contrast. So before I have "clicked" on the end date the text is black and I think it would be nice if it was white.
> > image
> > Then when I click maybe it would be more readable if the light pink was slightlyy darker. I think having white text is nice but maybe the contrast could be stronger? Maybe Flynn has thoughts about this too haha
> > image
> 
> Interesting that for you the text shows up black if the end date is not selected. 
For me it is like this: 
image
As for the contrast, I agree its not perfect. Perhaps this could be changed later ahaha

**Review by Denijar — APPROVED** [review]
Yep seems to work well as both organiser and attendee! Nice :))

**Pull request merged**
